### PR TITLE
Integrated API for RSA key generation, message encryption and decryption

### PR DESCRIPTION
**Pull request by Ista2000**

### CODE REVIEW

**Review by kishansairam9 — APPROVED** [review]
👍

**Comment by kishansairam9** [comment]
Please check these once : @Ista2000 
- [ ] Alert when no RSA key is selected (previously with js only, it was enabled)
- [ ] Decryption time is always being shown 0 ms

**Comment by Ista2000** [comment]
- Alert is not a priority as of now
- Decryption is hardcoded as of now

You can merge whatever I have done, as the API is completely written and functional and raise these as issues.

**Comment by kishansairam9** [comment]
Merged :+1:

**Pull request merged**
